@ApiVersioning.Sample_HostAddress = http://localhost:5208

# v1 - List (URL segment)
GET {{ApiVersioning.Sample_HostAddress}}/api/v1.0/blogs
Accept: application/json

###

# v1 - Get by id (shared endpoint)
GET {{ApiVersioning.Sample_HostAddress}}/api/v1.0/blogs/42
Accept: application/json

###

# v2 - Paged list (URL segment)
GET {{ApiVersioning.Sample_HostAddress}}/api/v2.0/blogs?page=2&pageSize=5
Accept: application/json

###

# v2 - Get by id (shared endpoint)
GET {{ApiVersioning.Sample_HostAddress}}/api/v2.0/blogs/42
Accept: application/json

###

# v3 - Preview / Deprecated (URL segment)
GET {{ApiVersioning.Sample_HostAddress}}/api/v3.0/blogs
Accept: application/json

###

# Health
GET {{ApiVersioning.Sample_HostAddress}}/api/health
Accept: application/json

###

# Examples showing alternate version readers (header / media-type / query)
# These demonstrate how the API Versioning is configured in Program.cs (Url segment is primary in controllers).
# Note: the controllers in this sample use URL-segment routes; header/query/media examples are included for reference.

### Header-based (X-Api-Version)
GET {{ApiVersioning.Sample_HostAddress}}/api/v2.0/blogs
X-Api-Version: 2.0
Accept: application/json

###

### Media type versioning (Accept header)
GET {{ApiVersioning.Sample_HostAddress}}/api/v2.0/blogs
Accept: application/json;v=2.0

###

### Query string versioning
GET {{ApiVersioning.Sample_HostAddress}}/api/v2.0/blogs?api-version=2.0&page=1&pageSize=10
Accept: application/json

###